# Dependencies for the Payment Service Component.
version: "3"

services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  redis:
    image: "redis/redis-stack"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
      - "8001:8001"

volumes:
  pgdata:
  redis-data:

